FROM alpine:latest 

WORKDIR /app 

COPY package.json ./ 

COPY pnpm-lock.yaml ./ 

COPY pnpm-workspace.yaml ./

COPY packages/databases ./packages/databases

COPY packages/services ./packages/services

COPY packages/eslint-config ./packages/eslint-config

COPY packages/typescript-config ./packages/typescript-config

COPY apps/notification-service ./apps/notification-service 

RUN apk add nodejs

RUN apk add npm

RUN npm install -g pnpm 

RUN pnpm install 

RUN pnpm --filter=notification-service build

EXPOSE 3000

CMD ["pnpm", "--filter", "notification-service", "start"]
