FROM alpine:latest 

WORKDIR /app 

COPY package.json ./ 

COPY pnpm-lock.yaml ./ 

COPY pnpm-workspace.yaml ./

COPY packages/databases ./packages/databases

COPY packages/typescript-config ./packages/typescript-config

COPY apps/scheduler-service ./apps/scheduler-service

RUN apk add nodejs

RUN apk add npm

RUN npm install -g pnpm 

RUN pnpm install 

# ✅ build shared packages first
RUN pnpm --filter=@letscode/databases build

RUN pnpm --filter=scheduler-service build

EXPOSE 3000

CMD ["pnpm", "--filter", "scheduler-service", "start"]
